--- # Contains default parameters for the microscope and all associated experiments.

# ----------------------------------------------- Photodiode parameters -----------------------------------------------

# Serial connection
tty: /dev/ttyACM0
baudrate:   9600    # Bit rate, ensure it matches that of the Arduino connection.

# ------------------------------------------------- Stage parameters  -------------------------------------------------

# I2C channel used to connect to motors. Varies depending on RPi model.
channel:              1

# Stage cannot be displaced by more than [x_bound, y_bound, z_bound] microsteps from [0, 0, 0] in any direction. Set
# 'override' to true to ignore these bounds.
xyz_bound:            [320000, 320000, 320000]

# Microsteps per step???
microsteps:           16

# Backlash in microsteps for the [x, y, z] motors respectively.
backlash:             [200, 200, 200]

override:             false

# --------------------------------------------- SensorScope GUI parameters ---------------------------------------------

# No. of microsteps per key press on GUI.
key_stepsize:         1000

# Control keys for the GUI.

exit:                 x

save:                 g

+x:                   s

-x:                   w

+y:                   d

-y:                   a

# Not sure about the exact direction of +z and -z.
+z:                   e

-z:                   q

# ---------------------------------------------- Experimental parameters ----------------------------------------------


# ---------------------------------------------------- RasterXY images ---------------------------------------------------
# The number of steps per axis to take i.e. generates an n+1 x n+1 images in total, and number of microsteps between
# each measurement.
raster_n_step:    [[64, 1000],
                   [9, 100]]

save_mode:        save_subset
# -------------------------------------------------- Laser alignment --------------------------------------------------

# The number of steps per axis to take i.e. generates an n+1 x n+1 images in total.
n_steps:            [[10, 50], [10, 25]]

parabola_N:           10

parabola_step:        50

# Align parabolically along each of x and y many times.
parabola_iterations:  1

# ------------------------------------------------------ Along Z ------------------------------------------------------

# List of positions to make sharpness measurements for. The format is [[n_z, microsteps], ...]. For example [[20, 1000],
# ...] will take sharpness measurements in intervals of 1000 microsteps from -1000 * 20 / 2 to +1000 * 20 / 2 resulting
# in 21 total measurements. It will then move to the region of highest sharpness and continue with the next set in the
# main list.
mmt_range:        [[10, 50]]
               #   [10, 200]
               #   [10  200]
               #   [12  100]]

# ------------------------------------------------ Drift and Recentre -------------------------------------------------

# How long in seconds to sleep for between initial alignment and drift measurement, as a list of times to measure in s.
sleep_times:      [100, 1000, 10000]

raster3d_n_step:    [[0, 1000]]

# Timed measurements at same spot.
N: 100
t: 1
...
